### ISSUE TITLE
Should find existing appointments be required?

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.Scheduling#10]
Should find existing appointments be required on the server?  If not, should it have a named option?

From discussion in room, it may be simpler as optional as the server would be implementing operations and not FHIR RESTful interactions while this is optional.

**Comment by vassilpeytchev** [comment]
The ability to search for FHIR resources is usually something that is available in generic FHIR servers. The only contribution of ITI-18 is the definition of the parameters for a search. I don;t think there is no need to call it out as a named option.
