### ISSUE TITLE
New parameters for $find operation

### ISSUE THREAD

**Issue by RicardoQuintano** [IHE/ITI.Scheduling#18]
**Section Number**:  2:3.115.4.1 Find Potential Appointments request

**Issue**
In our solutions we use a set of parameters to search for Slots (appointments). These parameters are not currently present in the $find opperation. 

**Proposed Change** 
Include the following parameters:
- InsurancePlan: code or reference. Some healthcare insurances (plan) can only schedule in specific healthcare providers/institutions.
- PatientGender: code.  Some Healthcare facilities in Brazil, due to the lack of security, do not schedule appointments for female patients in the night period.
- PatientWeight: quantity. Some patients due to their weight can not use some devices (e.g., CT Scan). Thus, they need a special device.

**Priority**: High

**Comment by vassilpeytchev** [comment]
@RicardoQuintano 

- I am investigating adding an InsurancePlan parameter
- There are two ways you can address this:
--     If the scheduling client knows that the time restriction applies generally to the request, it can use the timing parameter to request no night appointments
--     If the time restriction applies to only some of the facilities, then the patientResource parameter will have the patient gender, and will allow the scheduling server to apply the time of day constraint when appropriate. I don't think a separate parameter is needed.
- I am investigating adding a Vital sign observation parameter that will be used to provide the weight,

**Comment by RicardoQuintano** [comment]
Hi @vassilpeytchev 

"_If the scheduling client knows that the time restriction applies generally to the request, it can use the timing parameter to request no night appointments_"
The client does not know if the facility is unsafe, thus will not use the timing parameter.

"_If the time restriction applies to only some of the facilities, then the patientResource parameter will have the patient gender, and will allow the scheduling server to apply the time of day constraint when appropriate. I don't think a separate parameter is needed._"
Got it. It makes sense. I think this will work well for us.

Thanks!
