### ISSUE TITLE
Operation Definition Binding column

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.Scheduling#24]
The binding column does not look like it is right. Putting a canonical as a simple string. 
https://build.fhir.org/ig/IHE/ITI.Scheduling/OperationDefinition-appointment-find.html

**Comment by JohnMoehrke** [comment]
note that one did work, two others did not

**Comment by vassilpeytchev** [comment]
This is something to do with the IG publisher, the structures are identical.

**Comment by vassilpeytchev** [comment]
This is something to do with the IG publisher.
