### ISSUE TITLE
[Bug]: Find Appointments - clarify the use of the term "actor"

### ISSUE THREAD

**Issue by regelkraut** [IHE/ITI.Scheduling#35]
### Contact Details

reinhard.egelkraut@cgm.com

### Section Number

[OperationDefinition: Find_Appointments_Operation](https://profiles.ihe.net/ITI/Scheduling/1.0.0-comment/OperationDefinition-appointment-find.html)
Comments below the table with the parameters, second bullet point

### What is wrong

The explanation in the second bullet point speaks about the behavior for multiple "actors". However, on first glance it is not clear which definition of actor is meant, the classical Actor from IHE or the actor element from the HL7 FHIR Resource Appointment -> Appointment.participant.actor.
(based on the context I assume it talks about the latter)

### Describe the solution you'd like

Add a short explanation that this comment talks about Appointment.participant.actor and not the IHE Actor, to avoid confusion.

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by vassilpeytchev** [comment]
This part definitely needs improved wording.
