### ISSUE TITLE
[Bug]: Appointment Profile, References to IPA

### ISSUE THREAD

**Issue by regelkraut** [IHE/ITI.Scheduling#36]
### Contact Details

reinhard.egelkraut@cgm.com

### Section Number

https://profiles.ihe.net/ITI/Scheduling/1.0.0-comment/StructureDefinition-ihe-sched-appt.html
Definition of Appointment.participant.actor 

### What is wrong

Appointment.participant.actor has currently a mandatory reference binding to the IPA-Patient and the IPA-Practitioner. Most of the countries do have dedicated national base/core profiles for Patient, Practitioner, etc. So, if they want to use the IHE Scheduling Profile in their domain they probably would like to apply their national base/core profiles as well. However, it seems like the current version of the profile for Appointment “forces” them to use the corresponding IPA profiles. Or will it be possible to replace the references with corresponding national profiles?

### Describe the solution you'd like

Remove the IPA references for Appointment.participant.actor and just use the regular reference for Patient and Practitioner.

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by vassilpeytchev** [comment]
Reference: https://fhir.hl7.at/r4-core-ballot_2021_01/StructureDefinition-austrian-patient.html

**Comment by JohnMoehrke** [comment]
I am not convinced that this Profile should bring in IPA, when we have in IHE ITI PDQm that has a Patient profile with actionable requirements on .identifier, and mCSD that has profiles of Practitioner. We must work with our own Profiles first.
