### ISSUE TITLE
[Bug]: No search parameter for HealthcareService in $find operation

### ISSUE THREAD

**Issue by sa-bre** [IHE/ITI.Scheduling#37]
### Contact Details

samuel.brendler@naboto.com

### Section Number

[OperationDefinition: Find_Appointments_Operation](https://build.fhir.org/ig/IHE/ITI.Scheduling/OperationDefinition-appointment-find.html#root)

### What is wrong

In the list of search parameters of the `$find` operation it would make sense to also be able to search for free appointments with a specific `HealthcareService`. The search parameter `specialty` might not be sufficient to narrow down the search in cases where a treatment exists in multiple variations. 
E.g. a massage could be offered with duration of 30 or 60 minutes, which can be represented as two separate `HealtcareServices`. In that case the patient would likely want to select only one of the two and see free appointments just for the selected type of massage when booking an appointment online.

### Describe the solution you'd like

Add search parameter `healthcare-service` in the same way as `practitioner` and `organization` to `$find` operation.

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by vassilpeytchev** [comment]
It is not clear how HealthcareService can provide additional details beyond specialty and location combinations. In the example given about 30 minute vs 60 minute massage, unless you have different codes for each duration, it doesn't seem that using the HealthcareService resource can help.
