### ISSUE TITLE
[Suggestion]: indicate that the Find Potential Appointments should not return appointments that are held

### ISSUE THREAD

**Issue by RicardoQuintano** [IHE/ITI.Scheduling#38]
### Contact Details

ricardo.quintano@philips.com

### What is wrong

I think it is important to indicate that the Find Potential Appointments should not return appointments that are held (using transaction ITI-116 - Hold appointments).

I would include this information in the following pages:

https://profiles.ihe.net/ITI/Scheduling/1.0.0-comment/ITI-115.html
https://profiles.ihe.net/ITI/Scheduling/1.0.0-comment/OperationDefinition-appointment-find.html

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by vassilpeytchev** [comment]
Clarification added.
