### ISSUE TITLE
[Discussion]: “squeezed” appointments

### ISSUE THREAD

**Issue by RicardoQuintano** [IHE/ITI.Scheduling#39]
### Contact Details

ricardo.quintano@philips.com

### What is wrong

Sometimes an appointment needs to be “squeezed” into the schedule.  For example, an emergency situation must be seen.  The clinician will attempt to squeeze the patient in between two scheduled appointments.  

How this scenario could be done using this IHE profile (IG) as this will create an appointment that does not yet exist?
Perhaps the ITI-117 could be extended to support this scenario.

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by vassilpeytchev** [comment]
A core assumption in this profile is that the scheduling server is responsible for the business logic of the determining what and when can be scheduled. The client doesn't need to know that there was anything ``squeezed``.

**Comment by vassilpeytchev** [comment]
Will add an example to Scope in Volume 1 to explain the separation of purpose.
